name: release

on:
  #  push:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  build:
    uses: philipseo/actions/actions/reusable-workflows/pnpm-build.yml@main
    with:
      pnpm-version: 9.11.0
